apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: uk1987/auth
          env:
            - name:  JWT_KEY
              valueFrom:
                secretKeyRef:
                  name:  jwt-secret
                  key:  JWT_KEY
            - name: NPM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: npm-secret
                  key: NPM_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000