apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
    useBuildkit: true  # Enable Docker BuildKit
  artifacts:
    - image: uk1987/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: uk1987/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
