apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: server
build:
  artifacts:
    - image: ticketing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/auth-mongo-depl.yml
